# Site settings

paulushc:
  name: Paulo Gomes
  email: paulushc@gmail.com
  web: https://www.linkedin.com/in/paulushc/
adafpc:
  name: Ada Ferreira
  web: https://www.twitter.com/adafpc

title: Paulo Gomes
email: paulushc@gmail.com
description: >- 
  Paulo Gomes, desenvolvedor, gamer, pai.
baseurl: "" 
url: "https://paulushcgcj.github.io/" 
github_username:  paulushcgcj
linkedin_username: paulushc
youtube_username: paulushc

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed  
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
